buildscript {
    apply from: 'versions.gradle'
    apply from: 'pro.gradle'

    repositories {
        google()
        mavenCentral() // add repository
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public' }
        maven { url 'https://repo1.maven.org/maven2/' }

        maven { url 'https://artifact.bytedance.com/repository/Volcengine/' }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://developer.hihonor.com/repo' }
        maven { url "https://artifact.bytedance.com/repository/Volcengine/" }
    }

    allprojects {
        repositories {
            google()
            mavenCentral()
            maven { url 'https://jitpack.io' }
            maven { url 'https://maven.aliyun.com/repository/central' }
            maven { url 'https://maven.aliyun.com/repository/jcenter' }
            maven { url 'https://maven.aliyun.com/repository/google' }
            maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
            maven { url 'https://maven.aliyun.com/repository/public' }
            maven { url 'https://maven.aliyun.com/nexus/content/groups/public' }
            maven { url 'https://repo1.maven.org/maven2/' }

            maven { url 'https://artifact.bytedance.com/repository/Volcengine/' }
            maven { url 'https://developer.huawei.com/repo/' }
            maven { url 'https://developer.hihonor.com/repo' }
            maven { url "https://artifact.bytedance.com/repository/Volcengine/" }
        }
    }

//    dependencies {
//        classpath 'com.github.kezong:fat-aar:1.3.8'
//    }

    rootProject.buildDir = "../build"
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
        project.evaluationDependsOn(":app")
    }
//
    tasks.register("clean", Delete) {
        delete rootProject.buildDir
    }
}
